import { createElement } from 'lwc';
import Temp1ServiceChild1Comp from 'c/temp1ServiceChild1Comp';

describe('c-temp1-service-child1-comp', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-temp1-service-child1-comp', {
            is: Temp1ServiceChild1Comp
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});